[phases.build]
cmds = [
  "npm install --prefix server --production",
  "npm install --prefix client",
  "npm run build --prefix client",
  "mkdir -p server/public",
  "cp -r client/dist/* server/public/ || echo 'No dist files to copy'"
]

[phases.start]
cmd = "node server/index.js"

[variables]
NODE_ENV = "production"
JWT_SECRET = "tech-board-2025-secure-jwt-secret-key-production"
PORT = "8080"