[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "npm install --omit=dev",
  "cd server && npm install --omit=dev",
  "cd client && npm install"
]

[phases.build]
cmds = [
  "cd client && npm run build",
  "mkdir -p server/public && cp -r client/dist/* server/public/",
  "mkdir -p server/database",
  "cd server && node create-build-db.js",
  "node test-server-startup.js",
  "node verify-deployment-ready.js",
  "echo 'Build complete - will start railway-production-server.js'"
]

[start]
cmd = "cd server && npm start"