[phases.setup]
nixPkgs = ["nodejs_20", "python3", "sqlite"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["node railway-build.js"]

[start]
cmd = "node railway-start.js"

[variables]
NODE_ENV = "production"
PORT = "8000"