[phases.build]
cmds = ["npm install --prefix server --production"]

[phases.start]
cmd = "node server/index.js"

[variables]
NODE_ENV = "production"
JWT_SECRET = "tech-board-2025-secure-jwt-secret-key-production"
PORT = "8080"