[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = [
  "npm install --prefix client --no-audit --no-fund",
  "npm install --prefix server --production --no-audit --no-fund"
]

[phases.build]
cmds = [
  "npm run build --prefix client",
  "mkdir -p server/public",
  "cp -r client/dist/* server/public/ || echo 'Build files copied'"
]

[phases.start]
cmd = "node server/start-production.js"

[variables]
NODE_ENV = "production"
JWT_SECRET = "tech-board-2025-railway-production-jwt-secret-key-v2"
PORT = "8080"
CORS_ORIGIN = "https://tech-board.up.railway.app"
RAILWAY_STATIC_URL = "https://tech-board.up.railway.app"
RATE_LIMIT_WINDOW_MS = "600000"
RATE_LIMIT_MAX = "500"
BCRYPT_ROUNDS = "10"
LOG_LEVEL = "info"
ENABLE_COMPRESSION = "true"
ENABLE_CACHE = "true"
CACHE_TTL = "300"
MAX_REQUEST_SIZE = "5mb"
TRUST_PROXY = "true"
RAILWAY_ENVIRONMENT = "production"