[build]
builder = "NIXPACKS"
buildCommand = "npm run railway:build"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "8000"
